"""
LLM provider configuration schemas.

This module defines field schemas for LLM provider configurations.
All schemas use the unified TypeSchema structure from base.py.
"""

from typing import Dict
from .base import FieldSchema, TypeSchema, convert_typed_schemas_to_dict

# Define LLM schemas using direct Pydantic models
LLM_FORM_SCHEMAS: Dict[str, TypeSchema] = {
    "openai": TypeSchema(
        name="OpenAI",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your OpenAI API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="gpt-3.5-turbo",
                options=[
                    {"value": "gpt-5", "label": "GPT 5"},
                    {"value": "gpt-5-mini", "label": "GPT 5 mini"},
                    {"value": "gpt-5-nano", "label": "GPT 5 nano"},
                    {"value": "gpt-5.1", "label": "GPT 5.1"},
                    {"value": "gpt-5.2", "label": "GPT 5.2"},
                    {"value": "gpt-4o", "label": "GPT-4o"},
                    {"value": "gpt-4o-mini", "label": "GPT-4o Mini"},
                    {"value": "gpt-4", "label": "GPT-4"},
                    {"value": "gpt-4-32k", "label": "GPT-4 32K"},
                    {"value": "gpt-4-turbo-preview", "label": "GPT-4 Turbo Preview"},
                    {"value": "o1-mini", "label": "O1 Mini"},
                    {"value": "o1-small", "label": "O1 Small"},
                    {"value": "o1-medium", "label": "O1 Medium"},
                    {"value": "o1-large", "label": "O1 Large"},
                    {"value": "gpt-3.5-turbo", "label": "GPT-3.5 Turbo"},
                    {"value": "gpt-3.5-turbo-16k", "label": "GPT-3.5 Turbo 16K"},
                ],
            ),
            FieldSchema(
                name="organization",
                type="text",
                label="Organization ID",
                required=False,
                description="Your OpenAI organization ID (optional)",
            ),
            FieldSchema(
                name="temperature",
                type="number",
                label="Temperature",
                required=False,
                default=0.7,
                min=0.0,
                max=2.0,
                step=0.1,
                description="Controls randomness (0.0 to 2.0)",
            ),
            FieldSchema(
                name="max_tokens",
                type="number",
                label="Max Tokens",
                required=False,
                default=1024,
                min=1,
                step=1,
                description="Maximum number of tokens to generate",
            ),
            FieldSchema(
                name="timeout",
                type="number",
                label="Timeout",
                required=False,
                default=60,
                min=1,
                step=1,
                description="Maximum time in seconds to wait for response",
            ),
            FieldSchema(
                name="max_retries",
                type="number",
                label="Max Retries",
                required=False,
                default=3,
                min=0,
                step=1,
                description="Maximum number of retry attempts",
            ),
        ],
    ),
    "google_genai": TypeSchema(
        name="Google Gemini",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Google AI API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="gemini-2.5-pro",
                options=[
                    {"value": "gemini-2.5-pro", "label": "Gemini Pro (2.5)"},
                    {"value": "gemini-3-pro-preview", "label": "Gemini 3 pro preview"},
                    {
                        "value": "gemini-3-flash-preview",
                        "label": "Gemini 3 flash preview",
                    },
                ],
            ),
            FieldSchema(
                name="project_id",
                type="text",
                label="Project ID",
                required=False,
                description="Your Google Cloud project ID (optional)",
            ),
            FieldSchema(
                name="temperature",
                type="number",
                label="Temperature",
                required=False,
                default=0.7,
                min=0.0,
                max=2.0,
                step=0.1,
                description="Controls randomness (0.0 to 2.0)",
            ),
            FieldSchema(
                name="max_tokens",
                type="number",
                label="Max Tokens",
                required=False,
                default=1024,
                min=1,
                step=1,
                description="Maximum number of tokens to generate",
            ),
        ],
    ),
    "llama": TypeSchema(
        name="Llama",
        fields=[
            FieldSchema(
                name="base_url",
                type="text",
                label="Base URL",
                required=True,
                description="URL of your Llama server (e.g., http://localhost:8000)",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="llama-2-7b-chat",
                options=[
                    {"value": "llama-2-7b-chat", "label": "Llama 2 7B Chat"},
                    {"value": "llama-2-13b-chat", "label": "Llama 2 13B Chat"},
                    {"value": "llama-2-70b-chat", "label": "Llama 2 70B Chat"},
                    {"value": "llama-2-7b-instruct", "label": "Llama 2 7B Instruct"},
                    {"value": "llama-2-13b-instruct", "label": "Llama 2 13B Instruct"},
                    {"value": "llama-2-70b-instruct", "label": "Llama 2 70B Instruct"},
                ],
            ),
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=False,
                description="API key if your server requires authentication",
            ),
            FieldSchema(
                name="context_window",
                type="number",
                label="Context Window",
                required=False,
                default=4096,
                min=1,
                step=1,
                description="Maximum context window size",
            ),
            FieldSchema(
                name="stop_sequences",
                type="tags",
                label="Stop Sequences",
                required=False,
                description="Sequences that stop generation (e.g., </s>, Human:)",
            ),
            FieldSchema(
                name="temperature",
                type="number",
                label="Temperature",
                required=False,
                default=0.7,
                min=0.0,
                max=2.0,
                step=0.1,
                description="Controls randomness (0.0 to 2.0)",
            ),
            FieldSchema(
                name="max_tokens",
                type="number",
                label="Max Tokens",
                required=False,
                default=1024,
                min=1,
                step=1,
                description="Maximum number of tokens to generate",
            ),
        ],
    ),
    "mistral": TypeSchema(
        name="Mistral",
        fields=[
            FieldSchema(
                name="base_url",
                type="text",
                label="Base URL",
                required=True,
                description="URL of your Mistral server (e.g., http://localhost:8000)",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="mistral-7b-instruct",
                options=[
                    {"value": "mistral-7b-instruct", "label": "Mistral 7B Instruct"},
                    {
                        "value": "mistral-7b-instruct-v0.2",
                        "label": "Mistral 7B Instruct v0.2",
                    },
                    {"value": "mistral-small", "label": "Mistral Small"},
                    {"value": "mistral-medium", "label": "Mistral Medium"},
                    {"value": "mistral-large", "label": "Mistral Large"},
                ],
            ),
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=False,
                description="API key if your server requires authentication",
            ),
            FieldSchema(
                name="context_window",
                type="number",
                label="Context Window",
                required=False,
                default=8192,
                min=1,
                step=1,
                description="Maximum context window size",
            ),
            FieldSchema(
                name="stop_sequences",
                type="tags",
                label="Stop Sequences",
                required=False,
                description="Sequences that stop generation (e.g., </s>, Human:)",
            ),
            FieldSchema(
                name="temperature",
                type="number",
                label="Temperature",
                required=False,
                default=0.7,
                min=0.0,
                max=2.0,
                step=0.1,
                description="Controls randomness (0.0 to 2.0)",
            ),
            FieldSchema(
                name="max_tokens",
                type="number",
                label="Max Tokens",
                required=False,
                default=1024,
                min=1,
                step=1,
                description="Maximum number of tokens to generate",
            ),
        ],
    ),
    "anthropic": TypeSchema(
        name="Anthropic",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Anthropic API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="claude-3-sonnet-20240229",
                options=[
                    {"value": "claude-3-sonnet-20240229", "label": "Claude 3 Sonnet"},
                    {"value": "claude-3-opus-20240229", "label": "Claude 3 Opus"},
                    {"value": "claude-3-haiku-20240307", "label": "Claude 3 Haiku"},
                ],
            ),
            FieldSchema(
                name="temperature",
                type="number",
                label="Temperature",
                required=False,
                default=0.7,
                min=0.0,
                max=2.0,
                step=0.1,
                description="Controls randomness (0.0 to 2.0)",
            ),
            FieldSchema(
                name="max_tokens",
                type="number",
                label="Max Tokens",
                required=False,
                default=1024,
                min=1,
                step=1,
                description="Maximum number of tokens to generate",
            ),
        ],
    ),
    "azure_openai": TypeSchema(
        name="Azure OpenAI",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Azure OpenAI API key",
            ),
            FieldSchema(
                name="base_url",
                type="text",
                label="Base URL",
                required=True,
                description="Your Azure OpenAI endpoint URL",
            ),
            FieldSchema(
                name="deployment_name",
                type="text",
                label="Deployment Name",
                required=True,
                description="Your Azure OpenAI deployment name",
            ),
            FieldSchema(
                name="api_version",
                type="text",
                label="API Version",
                required=True,
                default="2024-02-15-preview",
                description="Azure OpenAI API version",
            ),
        ],
    ),
    "google_vertexai": TypeSchema(
        name="Google Vertex AI",
        fields=[
            FieldSchema(
                name="project_id",
                type="text",
                label="Project ID",
                required=True,
                description="Your Google Cloud project ID",
            ),
            FieldSchema(
                name="location",
                type="text",
                label="Location",
                required=True,
                default="us-central1",
                description="Google Cloud location",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="gemini-pro",
                options=[
                    {"value": "gemini-pro", "label": "Gemini Pro"},
                    {"value": "gemini-pro-vision", "label": "Gemini Pro Vision"},
                ],
            ),
        ],
    ),
    "cohere": TypeSchema(
        name="Cohere",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Cohere API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="command",
                options=[
                    {"value": "command", "label": "Command"},
                    {"value": "command-light", "label": "Command Light"},
                    {"value": "command-r", "label": "Command R"},
                    {"value": "command-r-plus", "label": "Command R Plus"},
                ],
            ),
        ],
    ),
    "bedrock": TypeSchema(
        name="Amazon Bedrock",
        fields=[
            FieldSchema(
                name="aws_access_key_id",
                type="password",
                label="AWS Access Key ID",
                required=False,
                description="Your AWS Access Key ID",
            ),
            FieldSchema(
                name="aws_secret_access_key",
                type="password",
                label="AWS Secret Access Key",
                required=False,
                description="Your AWS Secret Access Key",
            ),
            FieldSchema(
                name="region_name",
                type="text",
                label="Region",
                required=False,
                default="ca-central-1",
                description="AWS region name",
            ),
            FieldSchema(
                name="model",
                type="text",
                label="Model",
                required=True,
                default="us.amazon.nova-2-lite-v1:0",
                description="AWS model name",
            ),
        ],
    ),
    "mistralai": TypeSchema(
        name="Mistral AI",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Mistral AI API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="mistral-small",
                options=[
                    {"value": "mistral-small", "label": "Mistral Small"},
                    {"value": "mistral-medium", "label": "Mistral Medium"},
                    {"value": "mistral-large", "label": "Mistral Large"},
                ],
            ),
        ],
    ),
    "groq": TypeSchema(
        name="Groq",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Groq API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="llama2-70b-4096",
                options=[
                    {"value": "llama2-70b-4096", "label": "Llama 2 70B"},
                    {"value": "mixtral-8x7b-32768", "label": "Mixtral 8x7B"},
                ],
            ),
        ],
    ),
    "ollama": TypeSchema(
        name="Ollama",
        fields=[
            FieldSchema(
                name="base_url",
                type="text",
                label="Base URL",
                required=True,
                default="http://localhost:11434",
                description="URL of your Ollama server",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="llama2",
                options=[
                    {"value": "llama2", "label": "Llama 2"},
                    {"value": "mistral:7b", "label": "Mistral 7B"},
                    {"value": "gpt-oss:20b", "label": "GPT-OSS 20B"},
                    {
                        "value": "llama3.3:70B-instruct-q4_K_M",
                        "label": "Llama 3.3 70B Q4",
                    },
                    {"value": "mistral:7b-instruct", "label": "Mistral 7B Instruct"},
                    {
                        "value": "mistral:7b-instruct-v0.2",
                        "label": "Mistral 7B Instruct v0.2",
                    },
                    {"value": "codellama", "label": "CodeLlama"},
                    {"value": "neural-chat", "label": "Neural Chat"},
                    {"value": "starling-lm", "label": "Starling LM"},
                ],
            ),
        ],
    ),
    "perplexity": TypeSchema(
        name="Perplexity",
        fields=[
            FieldSchema(
                name="api_key",
                type="password",
                label="API Key",
                required=True,
                description="Your Perplexity API key",
            ),
            FieldSchema(
                name="model",
                type="select",
                label="Model",
                required=True,
                default="sonar-small-chat",
                options=[
                    {"value": "sonar-small-chat", "label": "Sonar Small Chat"},
                    {"value": "sonar-medium-chat", "label": "Sonar Medium Chat"},
                    {"value": "sonar-small-online", "label": "Sonar Small Online"},
                    {"value": "sonar-medium-online", "label": "Sonar Medium Online"},
                ],
            ),
        ],
    ),
}

LLM_FORM_SCHEMAS_DICT = convert_typed_schemas_to_dict(LLM_FORM_SCHEMAS)
