import time
import logging
import uuid
import json
from typing import List, Dict, Any, Optional
from uuid import UUID
from app.modules.workflow.manage.workflow_manager import WorkflowManager
from app.schemas.agent import AgentCreate, AgentRead
from app.services.agent_config import AgentConfigService
from fastapi import APIRouter, Depends, HTTPException, status, Request, Body
from fastapi_injector import Injected
from app.modules.workflow.utils import generate_python_function_template

from app.schemas.workflow import Workflow, WorkflowCreate, WorkflowUpdate
from app.auth.dependencies import auth, permissions

from app.services.workflow import WorkflowService
from app.dependencies.injector import injector
from app.modules.workflow.llm.provider import LLMProvider
from app.modules.workflow.engine.workflow_engine import WorkflowEngine
from app.core.permissions.constants import Permissions as P
from app.schemas.dynamic_form_schemas.nodes import NODE_DIALOG_SCHEMAS


router = APIRouter()
logger = logging.getLogger(__name__)



@router.post(
    "/config/from-wizard",
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(auth), Depends(permissions(P.Workflow.CREATE))],
)
async def create_workflow_from_wizard(
    request: Request,
    workflow_name: str=Body(...),
    workflow_json: str=Body(...),
    service: WorkflowService = Injected(WorkflowService),
    agent_service = Injected(AgentConfigService),
    workflow_service: WorkflowService = Injected(WorkflowService),
):
    """
    - Create a new Agent
    - Create a new workflow based on the wizard JSON

    """
    current_user = ""
    try:
        current_user = request.state.user
    except Exception as e:
        logger.error(f"Error getting current user: {e}")


    # Generate a agent record   

    agent_create = AgentCreate(
        name=workflow_name,
        description=f"Agent created from wizard: {workflow_name}",
        is_active=True,
        welcome_message=f"Hello! \nI am {workflow_name},\nHow can I assist you today?",
        welcome_title="Tell me your Today's creative idea!",
        possible_queries=[],
    )
    agent_result = await agent_service.create(agent_create, user_id=current_user.id if current_user else None)
    agent_id= agent_result.id #str(uuid.uuid4())



    # load & update workflow record
    workflow_id= agent_result.workflow_id # str(uuid.uuid4())
    url = request.url._url.replace(
        "/api/workflow-manager/config/from-wizard", f"/ai-agents/workflow/{agent_id}")
    
    # load workflow to update with json generated by agent wizard 
    workflow_record = await workflow_service.get_by_id(workflow_id)
    
    #generate workflow nodes and edges from wizard json
    workflow_engine = WorkflowManager(
        name=workflow_record.name,
        description=workflow_record.description,
        user_id=workflow_record.user_id,
        agent_id=workflow_record.agent_id,
        workflow_id=workflow_record.id,
    )

    json_workflow = json.loads(workflow_json)
    workflow_record.nodes = workflow_engine.generate_nodes_from_wizard(input_data=json_workflow)
    workflow_record.edges = [] # workflow_engine.generate_edges_from_wizard(input_data=json_workflow)
    workflow_record.executionState = workflow_engine.generate_execution_state_from_wizard(input_data=json_workflow) # required not to crash Studio
    workflow_record.testInput = {}

    workflow_record_updated = await workflow_service.update(workflow_id=workflow_id, data=workflow_record)



    return_Workflow = {
        "id": workflow_id,
        "name": workflow_name,
        "description": workflow_record.description,
        "user_id": workflow_record.user_id,
        "agent_id": workflow_record.agent_id,
        "url": url,
        "worflow_json": workflow_json,
        "db_record": workflow_record.model_dump(),
    }
    #workflow = await service.create(workflow)
    logger.info(f"Creating workflow from wizard: {workflow_name}")
    logger.info(f"Workflow JSON: {return_Workflow}")
    return return_Workflow



@router.get(
    "/config/available-node-types",
    dependencies=[Depends(auth)]
)
async def get_available_node_types():
    return list(NODE_DIALOG_SCHEMAS.keys())

# @router.get(
#     "",
#     response_model=List[Workflow],
#     dependencies=[Depends(auth), Depends(permissions("read:workflow"))],
# )
# async def get_workflows(service: WorkflowService = Injected(WorkflowService)):
#     """
#     Get all workflows for the current user
#     """
#     workflows = await service.get_all()
#     return workflows

