"""short description of change

Revision ID: 9cb2157febd6
Revises: ef7f8130f9f1
Create Date: 2025-06-27 00:20:03.382289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb2157febd6'
down_revision: Union[str, None] = 'ef7f8130f9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('agent_id', sa.UUID(), nullable=True), if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'agent_id', if_exists=True)
    # ### end Alembic commands ###
