"""Add llm_provider_id to knowledge_bases

Revision ID: 45397ece3bf0
Revises: 32ba037e619c
Create Date: 2025-06-05 15:04:54.887264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45397ece3bf0'
down_revision: Union[str, None] = '32ba037e619c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('llm_provider_id', sa.UUID(), nullable=True), if_not_exists=True)
    op.create_foreign_key(None, 'knowledge_bases', 'llm_providers', ['llm_provider_id'], ['id'], if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_bases', type_='foreignkey')
    op.drop_column('knowledge_bases', 'llm_provider_id', if_exists=True)
    # ### end Alembic commands ###
