"""add password force update date

Revision ID: 32ba037e619c
Revises: 48df9c298dd9
Create Date: 2025-05-30 12:36:07.513900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ba037e619c'
down_revision: Union[str, None] = '48df9c298dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('force_upd_pass_date', sa.DateTime(timezone=True), nullable=True), if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_upd_pass_date', if_exists=True)
    # ### end Alembic commands ###
