"""add url in knowledge bases

Revision ID: ef7f8130f9f1
Revises: 00006
Create Date: 2025-06-19 12:33:48.255945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7f8130f9f1'
down_revision: Union[str, None] = '00006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_name_key'), 'agents', type_='unique', if_exists=True)
    op.add_column('knowledge_bases', sa.Column('url', sa.String(length=255), nullable=True), if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'url', if_exists=True)
    op.create_unique_constraint(op.f('agents_name_key'), 'agents', ['name'], if_not_exists=True)
    # ### end Alembic commands ###
