"""add zendesk ticket id to conversation

Revision ID: 00006
Revises: 45397ece3bf0
Create Date: 2025-06-09 11:56:44.069703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00006'
down_revision: Union[str, None] = '45397ece3bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('zendesk_ticket_id', sa.Integer(), nullable=True), if_not_exists=True)
    op.create_unique_constraint(None, 'conversations', ['zendesk_ticket_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_column('conversations', 'zendesk_ticket_id', if_exists=True)
    # ### end Alembic commands ###
