"""workflow add testInput

Revision ID: 18e516fd77b5
Revises: 9cb2157febd6
Create Date: 2025-07-01 14:00:19.024712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18e516fd77b5'
down_revision: Union[str, None] = '9cb2157febd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('testInput', postgresql.JSONB(astext_type=sa.Text()), nullable=True),if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'testInput', if_exists=True)
    # ### end Alembic commands ###
