"""add topic and negative reason in conversation

Revision ID: 814b8735d398
Revises: 337da85423c3
Create Date: 2025-08-25 09:20:06.917336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814b8735d398'
down_revision: Union[str, None] = '337da85423c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('topic', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('negative_reason', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'webhooks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='unique')
    op.drop_column('conversations', 'negative_reason')
    op.drop_column('conversations', 'topic')
    # ### end Alembic commands ###
