"""add conversation feedback column

Revision ID: 7f3db8f0aa8c
Revises: 14d1518f79c1
Create Date: 2025-09-08 14:39:40.770779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3db8f0aa8c'
down_revision: Union[str, None] = '14d1518f79c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'feedback')
    # ### end Alembic commands ###
