"""add thinking phrases

Revision ID: 52e87b8cf30e
Revises: 7f3db8f0aa8c
Create Date: 2025-09-08 14:04:06.986192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e87b8cf30e'
down_revision: Union[str, None] = '7f3db8f0aa8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('thinking_phrases', sa.String(
        length=500), server_default='Thinking...', nullable=False))
    op.create_unique_constraint(None, 'webhooks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='unique')
    op.drop_column('agents', 'thinking_phrases')
    # ### end Alembic commands ###
