"""workflow add testInput

Revision ID: 18e516fd77b6
Revises: 18e516fd77b5
Create Date: 2025-07-05 13:20:19.024712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18e516fd77b6'
down_revision: Union[str, None] = '18e516fd77b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('original_filename', sa.String(length=1024), nullable=True),if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'original_filename', if_exists=True)
    # ### end Alembic commands ###
