"""add legra finalized column

Revision ID: d1563f55ff5c
Revises: 18e516fd77b6
Create Date: 2025-07-08 11:18:19.646199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1563f55ff5c'
down_revision: Union[str, None] = '18e516fd77b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('legra_finalize', sa.Boolean(), nullable=True))
    op.alter_column('recordings', 'original_filename',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'original_filename',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.drop_column('knowledge_bases', 'legra_finalize')
    # ### end Alembic commands ###
