"""add_more_config_to_agent

Revision ID: 7d5878ee6550
Revises: 52e87b8cf30e
Create Date: 2025-09-11 15:35:49.474408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5878ee6550'
down_revision: Union[str, None] = '52e87b8cf30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('welcome_image', sa.LargeBinary(), nullable=True))
    op.add_column('agents', sa.Column('welcome_title', sa.String(length=200), nullable=True))
    op.add_column('agents', sa.Column('thinking_phrase_delay', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'webhooks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='unique')
    op.drop_column('agents', 'thinking_phrase_delay')
    op.drop_column('agents', 'welcome_title')
    op.drop_column('agents', 'welcome_image')
    # ### end Alembic commands ###
