"""execution state on workflow

Revision ID: 14d1518f79c1
Revises: 814b8735d398
Create Date: 2025-08-22 12:17:39.837935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14d1518f79c1'
down_revision: Union[str, None] = '814b8735d398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'webhooks', ['id'])
    op.add_column('workflows', sa.Column('executionState', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'executionState')
    op.drop_constraint(None, 'webhooks', type_='unique')
    # ### end Alembic commands ###
