"""added_ml_table

Revision ID: 294446b276e4
Revises: 7d5878ee6550
Create Date: 2025-10-13 14:29:34.723381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '294446b276e4'
down_revision: Union[str, None] = '92add2949f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('model_type', sa.Enum('XGBOOST', 'RANDOM_FOREST', 'LINEAR_REGRESSION', 'LOGISTIC_REGRESSION', 'OTHER', name='model_type_enum', create_constraint=True), nullable=False),
    sa.Column('pkl_file', sa.String(length=500), nullable=True),
    sa.Column('features', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('target_variable', sa.String(length=255), nullable=False),
    sa.Column('inference_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_ml_models_name', 'ml_models', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ml_models_name', table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
