"""add allowed enum to file status

Revision ID: d36b22c4663e
Revises: 8f93290cf8a7
Create Date: 2025-11-03 14:43:52.714341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36b22c4663e'
down_revision: Union[str, None] = '8f93290cf8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE filestatus ADD VALUE 'PROCESSED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
