"""add_ml_model_pipeline_tables

Revision ID: b152ce8a0a1c
Revises: d4698bfbfce3
Create Date: 2025-11-25 16:20:21.715208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b152ce8a0a1c'
down_revision: Union[str, None] = 'c999ae176763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model_pipeline_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_configs_model_id', 'ml_model_pipeline_configs', ['model_id'], unique=False)
    op.create_index('idx_pipeline_configs_workflow_id', 'ml_model_pipeline_configs', ['workflow_id'], unique=False)
    op.create_table('ml_model_pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_config_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipeline_run_status_enum', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_config_id'], ['ml_model_pipeline_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_runs_config_id', 'ml_model_pipeline_runs', ['pipeline_config_id'], unique=False)
    op.create_index('idx_pipeline_runs_created_at', 'ml_model_pipeline_runs', ['created_at'], unique=False)
    op.create_index('idx_pipeline_runs_model_id', 'ml_model_pipeline_runs', ['model_id'], unique=False)
    op.create_index('idx_pipeline_runs_model_status', 'ml_model_pipeline_runs', ['model_id', 'status'], unique=False)
    op.create_index('idx_pipeline_runs_status', 'ml_model_pipeline_runs', ['status'], unique=False)
    op.create_table('ml_model_pipeline_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('MODEL_FILE', 'METRICS', 'LOGS', 'DATA', 'OTHER', name='artifact_type_enum', create_constraint=True), nullable=False),
    sa.Column('artifact_path', sa.String(length=1000), nullable=False),
    sa.Column('artifact_name', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['ml_model_pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_artifacts_run_id', 'ml_model_pipeline_artifacts', ['pipeline_run_id'], unique=False)
    op.create_index('idx_pipeline_artifacts_type', 'ml_model_pipeline_artifacts', ['artifact_type'], unique=False)
    
    # Handle webhook constraint/index changes (conditional - may not exist)
    # Drop constraint if it exists
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'webhooks_name_key' 
                AND conrelid = 'webhooks'::regclass
            ) THEN
                ALTER TABLE webhooks DROP CONSTRAINT webhooks_name_key;
            END IF;
        END $$;
    """)
    
    # Drop index if it exists
    op.execute("""
        DROP INDEX IF EXISTS ix_webhooks_name;
    """)
    
    # Create new unique index
    op.create_index(op.f('ix_webhooks_name'), 'webhooks', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_name'), table_name='webhooks')
    op.create_index(op.f('ix_webhooks_name'), 'webhooks', ['name'], unique=False)
    op.create_unique_constraint(op.f('webhooks_name_key'), 'webhooks', ['name'])
    op.drop_index('idx_pipeline_artifacts_type', table_name='ml_model_pipeline_artifacts')
    op.drop_index('idx_pipeline_artifacts_run_id', table_name='ml_model_pipeline_artifacts')
    op.drop_table('ml_model_pipeline_artifacts')
    op.drop_index('idx_pipeline_runs_status', table_name='ml_model_pipeline_runs')
    op.drop_index('idx_pipeline_runs_model_status', table_name='ml_model_pipeline_runs')
    op.drop_index('idx_pipeline_runs_model_id', table_name='ml_model_pipeline_runs')
    op.drop_index('idx_pipeline_runs_created_at', table_name='ml_model_pipeline_runs')
    op.drop_index('idx_pipeline_runs_config_id', table_name='ml_model_pipeline_runs')
    op.drop_table('ml_model_pipeline_runs')
    op.drop_index('idx_pipeline_configs_workflow_id', table_name='ml_model_pipeline_configs')
    op.drop_index('idx_pipeline_configs_model_id', table_name='ml_model_pipeline_configs')
    op.drop_table('ml_model_pipeline_configs')
    # ### end Alembic commands ###
