"""add tenant management table

Revision ID: 5fb6bb9a2506
Revises: 294446b276e4
Create Date: 2025-10-24 00:11:19.747477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818246258835'
down_revision: Union[str, None] = '818246258834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('database_name', sa.String(
                        length=255), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('domain', sa.String(length=255), nullable=True),
                    sa.Column('subdomain', sa.String(
                        length=100), nullable=True),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('created_by', sa.UUID(), nullable=True),
                    sa.Column('updated_by', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
                    sa.Column('is_deleted', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    # ### end Alembic commands ###
