"""add job and file for fine tuning open ai tables

Revision ID: 3c8d39f609ce
Revises: 818246258835
Create Date: 2025-10-29 11:35:04.864716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c8d39f609ce'
down_revision: Union[str, None] = '818246258835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openai_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openai_file_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'DELETED', 'ERROR', name='filestatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openai_files_openai_file_id'), 'openai_files', ['openai_file_id'], unique=True)
    op.create_table('fine_tuning_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openai_job_id', sa.String(), nullable=False),
    sa.Column('training_file_id', sa.UUID(), nullable=False),
    sa.Column('validation_file_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suffix', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('VALIDATING_FILES', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('fine_tuned_model', sa.String(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('trained_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_file_id'], ['openai_files.id'], ),
    sa.ForeignKeyConstraint(['validation_file_id'], ['openai_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_tuning_jobs_openai_job_id'), 'fine_tuning_jobs', ['openai_job_id'], unique=True)
    op.create_index(op.f('ix_fine_tuning_jobs_status'), 'fine_tuning_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fine_tuning_jobs_status'), table_name='fine_tuning_jobs')
    op.drop_index(op.f('ix_fine_tuning_jobs_openai_job_id'), table_name='fine_tuning_jobs')
    op.drop_table('fine_tuning_jobs')
    op.drop_index(op.f('ix_openai_files_openai_file_id'), table_name='openai_files')
    op.drop_table('openai_files')
    # ### end Alembic commands ###
