"""agent security

Revision ID: 2e57789f2740
Revises: b0866dc731f9
Create Date: 2026-01-24 03:39:17.644018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e57789f2740"
down_revision: Union[str, None] = "b0866dc731f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "agent_security_settings",
        sa.Column(
            "token_based_auth", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.drop_constraint(
        op.f("agents_security_settings_id_fkey"), "agents", type_="foreignkey"
    )
    op.drop_column("agents", "token_based_auth")
    op.drop_column("agents", "security_settings_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "security_settings_id", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "agents",
        sa.Column(
            "token_based_auth",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("agents_security_settings_id_fkey"),
        "agents",
        "agent_security_settings",
        ["security_settings_id"],
        ["id"],
    )
    op.drop_column("agent_security_settings", "token_based_auth")
    # ### end Alembic commands ###
