"""add file manager tables

Revision ID: c7f8d9e0f123
Revises: b0866dc731f9
Create Date: 2025-01-XX XX:XX:XX.XXXXXX

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f8d9e0f123'
down_revision: Union[str, None] = 'b0866dc731f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create files table
    op.create_table('files',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=500), nullable=False),
        sa.Column('path', sa.String(length=1000), nullable=False),
        sa.Column('size', sa.BigInteger(), nullable=True),
        sa.Column('mime_type', sa.String(length=255), nullable=True),
        sa.Column('storage_provider', sa.String(length=50), nullable=False),
        sa.Column('storage_path', sa.String(length=1000), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('file_extension', sa.String(length=10), nullable=True),
        sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Integer(), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('updated_by', sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
    )
    op.create_index('idx_files_path', 'files', ['path'], unique=False)
    op.create_index('idx_files_storage_provider', 'files', ['storage_provider'], unique=False)
    op.create_index('idx_files_storage_path', 'files', ['storage_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_files_storage_path', table_name='files')
    op.drop_index('idx_files_storage_provider', table_name='files')
    op.drop_index('idx_files_path', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
