"""agent settings

Revision ID: b0866dc731f9
Revises: b6ebad5ee664
Create Date: 2026-01-24 03:09:20.269137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b0866dc731f9"
down_revision: Union[str, None] = "b6ebad5ee664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_security_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("token_expiration_minutes", sa.Integer(), nullable=True),
        sa.Column("cors_allowed_origins", sa.Text(), nullable=True),
        sa.Column(
            "rate_limit_conversation_start_per_minute", sa.Integer(), nullable=True
        ),
        sa.Column(
            "rate_limit_conversation_start_per_hour", sa.Integer(), nullable=True
        ),
        sa.Column(
            "rate_limit_conversation_update_per_minute", sa.Integer(), nullable=True
        ),
        sa.Column(
            "rate_limit_conversation_update_per_hour", sa.Integer(), nullable=True
        ),
        sa.Column("recaptcha_enabled", sa.Boolean(), nullable=True),
        sa.Column("recaptcha_project_id", sa.String(length=200), nullable=True),
        sa.Column("recaptcha_site_key", sa.String(length=200), nullable=True),
        sa.Column("recaptcha_min_score", sa.String(length=10), nullable=True),
        sa.Column("gcp_svc_account", sa.Text(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_security_settings_agent_id"),
        "agent_security_settings",
        ["agent_id"],
        unique=True,
    )
    op.add_column("agents", sa.Column("security_settings_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "agents", "agent_security_settings", ["security_settings_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "agents", type_="foreignkey")
    op.drop_column("agents", "security_settings_id")
    sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
    sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column(
        "metadata",
        postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        autoincrement=False,
        nullable=True,
    ),
    sa.Column(
        "created_at",
        postgresql.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        autoincrement=False,
        nullable=True,
    ),
    sa.PrimaryKeyConstraint("id", name=op.f("vector_store_tenant_master_default_pkey"))

    op.drop_index(
        op.f("ix_agent_security_settings_agent_id"),
        table_name="agent_security_settings",
    )
    op.drop_table("agent_security_settings")
    # ### end Alembic commands ###
