"""log_agent_response

Revision ID: 410a77facee8
Revises: c9e0f1234567
Create Date: 2026-02-26 11:35:38.715655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "410a77facee8"
down_revision: Union[str, None] = "c9e0f1234567"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_response_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transcript_message_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=False),
        sa.Column("logged_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["transcript_message_id"], ["transcript_messages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_response_logs_conversation_id"),
        "agent_response_logs",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_response_logs_transcript_message_id"),
        "agent_response_logs",
        ["transcript_message_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agent_response_logs_transcript_message_id"),
        table_name="agent_response_logs",
    )
    op.drop_index(
        op.f("ix_agent_response_logs_conversation_id"), table_name="agent_response_logs"
    )
    op.drop_table("agent_response_logs")
    # ### end Alembic commands ###
