"""translation_support

Revision ID: bbf0dbf460f4
Revises: f3c9e2b7a1d4
Create Date: 2026-03-04 16:01:25.274570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bbf0dbf460f4"
down_revision: Union[str, None] = "f3c9e2b7a1d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("default", sa.String(), nullable=True),
        sa.Column("en", sa.String(), nullable=True),
        sa.Column("es", sa.String(), nullable=True),
        sa.Column("fr", sa.String(), nullable=True),
        sa.Column("de", sa.String(), nullable=True),
        sa.Column("pt", sa.String(), nullable=True),
        sa.Column("zh", sa.String(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="translations_pk"),
        sa.UniqueConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_table("translations")
    # ### end Alembic commands ###
